apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-work-cluster
  region: ap-northeast-2

vpc:
  id: "vpc-0ae18812742e23cb0"
  subnets:
    public:
      ap-northeast-2a:
          id: "subnet-083405bcd14ac0c05"
      ap-northeast-2b: 
          id: "subnet-0c30cba8eab190f8e"
      ap-northeast-2c
          id: "subnet-058ed18ca88316976"

nodeGroups:
  - name: eks-work-nodesgroup
    labels: { role: workers }
    instanceType: t3.micro
    desiredCapacity: 2
